---
timeout: 180
instances: 1
memory: 512M
#buildpack: toms-java-buildpack
env:
    SPRING_PROFILES_DEFAULT: cloud
    JAVA_OPTS: -Djava.security.egd=file:///dev/urandom
#    comment out for single standalone node or modify to point to Eureka peer
#    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server2.emea.fe.gopivotal.com/eureka/
applications:
- name: config-server1
  path: config-server/build/libs/config-0.2.jar
  hosts:
    - config-server1
    - config
